site_name: Split Raster
site_url: https://cuicaihao.github.io/split_raster/
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - GIS-RS: gis.md
  - Contributing: CONTRIBUTING.md
  - About: about.md
theme: readthedocs
